# Copyright 2024 8 Hobbies, LLC <hong@8hobbies.com>
#
# Licensed under the Apache License, Version 2.0(the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Npm Runtime

on:
  workflow_call:
    inputs:
      node-versions:
        description: "Node versions. The first version is the main version that tests on all OSes."
        default: '["22.x", "20.x", "18.x"]'
        type: string
        required: false
      os-versions:
        description: "Operating Systems. The first OS is the main OS that tests all Node versions on."
        default: '["ubuntu-24.04", "macos-15", "windows-2022"]'
        type: string
        required: false

jobs:
  setup:
    name: Runtime Matrix Setup
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          repository: "8hobbies/workflows"
      - name: Use Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: package.json
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Process inputs
        id: matrix
        run: npx tsx scripts/convert-node-os-versions.ts '${{ inputs.node-versions }}' '${{ inputs.os-versions }}' >> $GITHUB_OUTPUT
      - name: Show setup result
        run: echo "${{ steps.matrix.outputs.value }}"

  test:
    name: Runtime
    runs-on: ${{ matrix.platform.osVersion }}
    needs: [setup]

    strategy:
      matrix:
        platform: ${{fromJSON(needs.setup.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Use Node.js ${{ matrix.platform.nodeVersion }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.platform.nodeVersion }}
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test
